/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package infosystem;
import com.sun.glass.events.KeyEvent;
import javax.swing.*;
import java.sql.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author MayankMS
 */
public class AddToStudents extends javax.swing.JFrame {
Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;

    /**
     * Creates new form AddToStudents
     */
    public AddToStudents() {
        initComponents();
         conn=db_conn.java_db();
        Update_table();
    }
    
 private void Update_table() {
    try{
        String sql ="Select StudentID, StName, StGender, StCategory, StQualification, students.StreamID, StreamName, StrEligibility, StreamDuration from streams, students where streams.StreamID = students.StreamID";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
       Tbl_op.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
    }
    finally {
            
            try{
                rs.close();
                pst.close();
                
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null, e);    
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TF_ID = new javax.swing.JTextField();
        TF_name = new javax.swing.JTextField();
        TF_Gender = new javax.swing.JTextField();
        TF_Category = new javax.swing.JTextField();
        TF_cid = new javax.swing.JTextField();
        TF_Qual = new javax.swing.JTextField();
        TF_Search = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        lbl_clr = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lbl_del = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lbl_upd = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lbl_add = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_op = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Training Management System");
        setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        setLocationByPlatform(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 100, 128));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(32, 45, 65));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(32, 45, 65));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("STUDENT ID");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 112, 20));

        jLabel2.setBackground(new java.awt.Color(32, 45, 65));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAME");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 112, -1));

        jLabel3.setBackground(new java.awt.Color(32, 45, 65));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("GENDER");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 112, 20));

        jLabel5.setBackground(new java.awt.Color(32, 45, 65));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CASTE");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 112, -1));

        jLabel6.setBackground(new java.awt.Color(32, 45, 65));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("COURSE ID");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 112, -1));

        jLabel8.setBackground(new java.awt.Color(32, 45, 65));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SEARCH BY ID");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel10.setBackground(new java.awt.Color(32, 45, 65));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("QUALIFICAITON");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 112, -1));

        TF_ID.setBackground(new java.awt.Color(32, 45, 65));
        TF_ID.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TF_ID.setForeground(new java.awt.Color(255, 255, 255));
        TF_ID.setBorder(null);
        TF_ID.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jPanel2.add(TF_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 160, 20));

        TF_name.setBackground(new java.awt.Color(32, 45, 65));
        TF_name.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TF_name.setForeground(new java.awt.Color(255, 255, 255));
        TF_name.setBorder(null);
        TF_name.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jPanel2.add(TF_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 160, 20));

        TF_Gender.setBackground(new java.awt.Color(32, 45, 65));
        TF_Gender.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TF_Gender.setForeground(new java.awt.Color(255, 255, 255));
        TF_Gender.setBorder(null);
        TF_Gender.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jPanel2.add(TF_Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 160, 20));

        TF_Category.setBackground(new java.awt.Color(32, 45, 65));
        TF_Category.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TF_Category.setForeground(new java.awt.Color(255, 255, 255));
        TF_Category.setBorder(null);
        TF_Category.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jPanel2.add(TF_Category, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 160, 20));

        TF_cid.setBackground(new java.awt.Color(32, 45, 65));
        TF_cid.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TF_cid.setForeground(new java.awt.Color(255, 255, 255));
        TF_cid.setBorder(null);
        TF_cid.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jPanel2.add(TF_cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 160, 20));

        TF_Qual.setBackground(new java.awt.Color(32, 45, 65));
        TF_Qual.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TF_Qual.setForeground(new java.awt.Color(255, 255, 255));
        TF_Qual.setBorder(null);
        TF_Qual.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jPanel2.add(TF_Qual, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 160, 20));

        TF_Search.setBackground(new java.awt.Color(32, 45, 65));
        TF_Search.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TF_Search.setForeground(new java.awt.Color(255, 255, 255));
        TF_Search.setToolTipText("Press Enter");
        TF_Search.setBorder(null);
        TF_Search.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        TF_Search.setName(""); // NOI18N
        TF_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TF_SearchKeyPressed(evt);
            }
        });
        jPanel2.add(TF_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 160, 20));

        jSeparator2.setBackground(new java.awt.Color(32, 45, 65));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 160, 20));

        jSeparator3.setBackground(new java.awt.Color(32, 45, 65));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 160, 10));

        jSeparator4.setBackground(new java.awt.Color(32, 45, 65));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 160, 10));

        jSeparator5.setBackground(new java.awt.Color(32, 45, 65));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 160, 10));

        jSeparator6.setBackground(new java.awt.Color(32, 45, 65));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 160, 10));

        jSeparator7.setBackground(new java.awt.Color(32, 45, 65));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 160, 10));

        jSeparator8.setBackground(new java.awt.Color(32, 45, 65));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 160, 10));

        jPanel4.setBackground(new java.awt.Color(0, 100, 128));
        jPanel4.setForeground(new java.awt.Color(0, 0, 102));

        lbl_clr.setBackground(new java.awt.Color(29, 40, 46));
        lbl_clr.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_clr.setForeground(new java.awt.Color(255, 255, 255));
        lbl_clr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_clr.setText("CLEAR");
        lbl_clr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_clr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_clrMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_clr, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_clr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 57, -1));

        jPanel8.setBackground(new java.awt.Color(0, 100, 128));
        jPanel8.setForeground(new java.awt.Color(0, 0, 102));

        lbl_del.setBackground(new java.awt.Color(29, 40, 46));
        lbl_del.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_del.setForeground(new java.awt.Color(255, 255, 255));
        lbl_del.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_del.setText("DELETE");
        lbl_del.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_del.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_delMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_del, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_del, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 57, -1));

        jPanel9.setBackground(new java.awt.Color(0, 100, 128));
        jPanel9.setForeground(new java.awt.Color(0, 0, 102));

        lbl_upd.setBackground(new java.awt.Color(29, 40, 46));
        lbl_upd.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_upd.setForeground(new java.awt.Color(255, 255, 255));
        lbl_upd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_upd.setText("UPDATE");
        lbl_upd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_upd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_updMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(lbl_upd, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_upd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 70, -1));

        jPanel10.setBackground(new java.awt.Color(0, 100, 128));
        jPanel10.setForeground(new java.awt.Color(0, 0, 102));

        lbl_add.setBackground(new java.awt.Color(204, 204, 204));
        lbl_add.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_add.setForeground(new java.awt.Color(255, 255, 255));
        lbl_add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_add.setText("ADD");
        lbl_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_add, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_add, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 57, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 410, 560));

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        Tbl_op.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        Tbl_op.setForeground(new java.awt.Color(51, 51, 51));
        Tbl_op.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tbl_op.setEnabled(false);
        Tbl_op.setGridColor(new java.awt.Color(255, 255, 255));
        Tbl_op.setRowHeight(20);
        Tbl_op.setSelectionBackground(new java.awt.Color(62, 226, 141));
        Tbl_op.setShowHorizontalLines(false);
        Tbl_op.setShowVerticalLines(false);
        jScrollPane1.setViewportView(Tbl_op);

        jPanel3.add(jScrollPane1);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 600, 400));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/infosystem/NIELIT-Logo.png"))); // NOI18N
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 90));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("MANAGE STUDENTS");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 470, 40));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 90));

        jPanel11.setBackground(new java.awt.Color(32, 45, 65));
        jPanel11.setForeground(new java.awt.Color(0, 0, 102));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(0, 90, 148));
        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("BACK");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 25));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 580, 90, -1));

        jPanel13.setBackground(new java.awt.Color(32, 45, 65));
        jPanel13.setForeground(new java.awt.Color(0, 0, 102));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(0, 90, 148));
        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("SHOW STUDENTS");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel13.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 25));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, -1, -1));

        jPanel14.setBackground(new java.awt.Color(32, 45, 65));
        jPanel14.setForeground(new java.awt.Color(0, 0, 102));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setBackground(new java.awt.Color(0, 90, 148));
        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("SHOW COURSES");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel14.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 25));

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF_SearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_SearchKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        try{
            String sql="select * from students where StudentID=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, TF_Search.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("StName");
                TF_name.setText(add1);
                String add2=rs.getString("StudentID");
                TF_ID.setText(add2);
                String add3=rs.getString("StCategory");
                TF_Category.setText(add3);
                String add4=rs.getString("StQualification");
                TF_Qual.setText(add4);
                String add5=rs.getString("StGender");
                TF_Gender.setText(add5);
                String add6=rs.getString("StreamID");
                TF_cid.setText(add6);
            }
           else if(!TF_Search.equals(rs.next())){
                   JOptionPane.showMessageDialog(null,"No Records Found!","",JOptionPane.ERROR_MESSAGE);
            }
        }
catch(SQLException e){
    JOptionPane.showMessageDialog(null, e);
}
    }
    }//GEN-LAST:event_TF_SearchKeyPressed

    private void lbl_clrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_clrMouseClicked
        // TODO add your handling code here:
          TF_ID.setText("");
        TF_cid.setText("");
        TF_Qual.setText("");
        TF_Gender.setText("");
        TF_Search.setText("");
        TF_ID.setText("");
        TF_name.setText("");
        TF_Category.setText("");
    }//GEN-LAST:event_lbl_clrMouseClicked

    private void lbl_delMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_delMouseClicked
        // TODO add your handling code here:
         int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete?","Delete Record",JOptionPane.YES_NO_OPTION);
        if(p==0){
       String sql ="delete from students where StudentID=? ";
            try{
                pst=conn.prepareStatement(sql);
                pst.setString(1, TF_ID.getText());
                pst.execute();

                JOptionPane.showMessageDialog(null,"Record Deleted");

            }catch(SQLException e){

                JOptionPane.showMessageDialog(null, e);
            }finally {

                try{
                    rs.close();
                    pst.close();

                }
                catch(SQLException e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        Update_table();}
    }//GEN-LAST:event_lbl_delMouseClicked

    private void lbl_updMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_updMouseClicked
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?","Update Record",JOptionPane.YES_NO_OPTION);
        if(p==0){
              try{

                String value1 = TF_ID.getText();
                String value2 = TF_name.getText();
                String value3 = TF_Gender.getText();
                String value5 = TF_cid.getText();
                String value8 = TF_Qual.getText();
                String sql= "update students set StudentID='"+value1+"',"
                        + " StName='"+value2+"',"
                        + "StGender='"+value3+"'"
                        + ",StreamID='"+value5+"'"
                        + ",StQualification='"+value8+"'"
                        + " where StudentID='"+value1+"' ";

                pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Record Updated");

            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
              finally {

                try{
                    rs.close();
                    pst.close();

                }
                catch(SQLException e){

                }
            }

        }
                Update_table();
    }//GEN-LAST:event_lbl_updMouseClicked

    private void lbl_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addMouseClicked
        // TODO add your handling code here:
               int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to add record?","Add Record",JOptionPane.YES_NO_OPTION);
        if(p==0){
             
            try{
            String sql="insert into students"
                    + " (StudentID, StName,"
                    + " StCategory, StreamID,"
                    + "StQualification, StGender) values(?,?,?,?,?,?) ";
             pst=conn.prepareStatement(sql);
                pst.setString(1,TF_ID.getText());
                pst.setString(2,TF_name.getText());
                pst.setString(3,TF_Category.getText());
                pst.setString(4,TF_cid.getText());
                pst.setString(5,TF_Qual.getText());
                pst.setString(6,TF_Gender.getText());
            
             pst.execute();
                JOptionPane.showMessageDialog(null,"Data is saved successfully");
                }
            catch(SQLException e)
            {
                    JOptionPane.showMessageDialog(null,e);
            }
                finally {

                try{
                    rs.close();
                    pst.close();

                }  
                
                catch(SQLException e){
                   JOptionPane.showMessageDialog(null,e);
                
            }
        
            }
            
        }
        Update_table();
    }//GEN-LAST:event_lbl_addMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        Update_table();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
       
    try{
    String Sql="select * from streams";
    pst=conn.prepareStatement(Sql);
    rs=pst.executeQuery(Sql);
    Tbl_op.setModel(DbUtils.resultSetToTableModel(rs));
    
    }
   catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jLabel17MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
               this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddToStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddToStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddToStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddToStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddToStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF_Category;
    private javax.swing.JTextField TF_Gender;
    private javax.swing.JTextField TF_ID;
    private javax.swing.JTextField TF_Qual;
    private javax.swing.JTextField TF_Search;
    private javax.swing.JTextField TF_cid;
    private javax.swing.JTextField TF_name;
    private javax.swing.JTable Tbl_op;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lbl_add;
    private javax.swing.JLabel lbl_clr;
    private javax.swing.JLabel lbl_del;
    private javax.swing.JLabel lbl_upd;
    // End of variables declaration//GEN-END:variables


}