/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package infosystem;
import com.sun.glass.events.KeyEvent;
import javax.swing.*;
import java.sql.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author MayankMS
 */
public class AddToCourses extends javax.swing.JFrame {
Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;
    /**
     * Creates new form AddToCourses
     */
    public AddToCourses() {
       
        initComponents();
        conn=db_conn.java_db();
        Update_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void Update_table() {
    try{
        String sql ="select * from streams";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
       Tbl_op.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(SQLException e){
    JOptionPane.showMessageDialog(null, e);
    }
    finally {
            
            try{
                rs.close();
                pst.close();
                
            }
            catch(SQLException e){
                
            }
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("info?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        streamsQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT s FROM Streams s");
        streamsList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : streamsQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TF_ID = new javax.swing.JTextField();
        TF_Type = new javax.swing.JTextField();
        TF_Name = new javax.swing.JTextField();
        TF_Duration = new javax.swing.JTextField();
        TF_Fees = new javax.swing.JTextField();
        TF_Elig = new javax.swing.JTextField();
        TF_Seats = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        TF_Search = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_op = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Training Management System");
        setBackground(new java.awt.Color(127, 55, 5));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 100, 128));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(32, 45, 65));
        jPanel7.setForeground(new java.awt.Color(0, 0, 102));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(0, 90, 148));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("BACK");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 57, 25));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, 57, -1));

        jPanel11.setBackground(new java.awt.Color(32, 45, 65));
        jPanel11.setForeground(new java.awt.Color(0, 0, 102));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(0, 90, 148));
        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("REFRESH");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 25));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 70, -1));

        jPanel3.setBackground(new java.awt.Color(32, 45, 65));
        jPanel3.setPreferredSize(new java.awt.Dimension(920, 600));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(32, 45, 65));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("COURSE ID");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 86, -1));

        jLabel2.setBackground(new java.awt.Color(32, 45, 65));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TYPE");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 86, -1));

        jLabel3.setBackground(new java.awt.Color(32, 45, 65));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAME");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 86, -1));

        jLabel4.setBackground(new java.awt.Color(32, 45, 65));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SEATS");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 86, -1));

        jLabel5.setBackground(new java.awt.Color(32, 45, 65));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DURATION");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 86, -1));

        jLabel6.setBackground(new java.awt.Color(32, 45, 65));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FEES");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 86, -1));

        jLabel7.setBackground(new java.awt.Color(32, 45, 65));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ELIGIBILITY");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 86, -1));

        TF_ID.setBackground(new java.awt.Color(32, 45, 65));
        TF_ID.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TF_ID.setForeground(new java.awt.Color(255, 255, 255));
        TF_ID.setBorder(null);
        TF_ID.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jPanel3.add(TF_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 150, 20));

        TF_Type.setBackground(new java.awt.Color(32, 45, 65));
        TF_Type.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TF_Type.setForeground(new java.awt.Color(255, 255, 255));
        TF_Type.setBorder(null);
        TF_Type.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jPanel3.add(TF_Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 150, 20));

        TF_Name.setBackground(new java.awt.Color(32, 45, 65));
        TF_Name.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TF_Name.setForeground(new java.awt.Color(255, 255, 255));
        TF_Name.setBorder(null);
        TF_Name.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jPanel3.add(TF_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 150, 20));

        TF_Duration.setBackground(new java.awt.Color(32, 45, 65));
        TF_Duration.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TF_Duration.setForeground(new java.awt.Color(255, 255, 255));
        TF_Duration.setBorder(null);
        TF_Duration.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jPanel3.add(TF_Duration, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 150, 20));

        TF_Fees.setBackground(new java.awt.Color(32, 45, 65));
        TF_Fees.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TF_Fees.setForeground(new java.awt.Color(255, 255, 255));
        TF_Fees.setBorder(null);
        TF_Fees.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jPanel3.add(TF_Fees, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 150, 20));

        TF_Elig.setBackground(new java.awt.Color(32, 45, 65));
        TF_Elig.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TF_Elig.setForeground(new java.awt.Color(255, 255, 255));
        TF_Elig.setBorder(null);
        TF_Elig.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jPanel3.add(TF_Elig, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 150, 20));

        TF_Seats.setBackground(new java.awt.Color(32, 45, 65));
        TF_Seats.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TF_Seats.setForeground(new java.awt.Color(255, 255, 255));
        TF_Seats.setBorder(null);
        TF_Seats.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jPanel3.add(TF_Seats, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 150, 20));

        jPanel2.setBackground(new java.awt.Color(0, 100, 128));
        jPanel2.setForeground(new java.awt.Color(0, 0, 102));

        jLabel11.setBackground(new java.awt.Color(29, 40, 46));
        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("CLEAR");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 57, -1));

        TF_Search.setBackground(new java.awt.Color(32, 45, 65));
        TF_Search.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TF_Search.setForeground(new java.awt.Color(255, 255, 255));
        TF_Search.setToolTipText("Press Enter");
        TF_Search.setBorder(null);
        TF_Search.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        TF_Search.setName(""); // NOI18N
        TF_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TF_SearchKeyPressed(evt);
            }
        });
        jPanel3.add(TF_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 150, 20));

        jPanel5.setBackground(new java.awt.Color(0, 100, 128));
        jPanel5.setForeground(new java.awt.Color(0, 0, 102));

        jLabel9.setBackground(new java.awt.Color(29, 40, 46));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("DELETE");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 57, -1));

        jPanel8.setBackground(new java.awt.Color(0, 100, 128));
        jPanel8.setForeground(new java.awt.Color(0, 0, 102));

        jLabel13.setBackground(new java.awt.Color(29, 40, 46));
        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("UPDATE");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 57, -1));

        jSeparator1.setBackground(new java.awt.Color(32, 45, 65));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 150, 10));

        jSeparator2.setBackground(new java.awt.Color(32, 45, 65));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 150, 20));

        jSeparator3.setBackground(new java.awt.Color(32, 45, 65));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 150, 10));

        jSeparator4.setBackground(new java.awt.Color(32, 45, 65));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 150, 10));

        jSeparator5.setBackground(new java.awt.Color(32, 45, 65));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 150, 10));

        jSeparator6.setBackground(new java.awt.Color(32, 45, 65));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 150, 10));

        jSeparator7.setBackground(new java.awt.Color(32, 45, 65));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 150, 10));

        jSeparator8.setBackground(new java.awt.Color(32, 45, 65));
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 150, 10));

        jPanel6.setBackground(new java.awt.Color(0, 100, 128));
        jPanel6.setForeground(new java.awt.Color(0, 0, 102));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ADD");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 57, -1));

        lblSearch.setBackground(new java.awt.Color(29, 40, 46));
        lblSearch.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblSearch.setForeground(new java.awt.Color(255, 255, 255));
        lblSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearch.setText("SEARCH BY ID");
        jPanel3.add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 110, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 400, 500));

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setBackground(new java.awt.Color(97, 212, 195));
        jScrollPane1.setBorder(null);

        Tbl_op.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        Tbl_op.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        Tbl_op.setEnabled(false);
        Tbl_op.setGridColor(new java.awt.Color(255, 255, 255));
        Tbl_op.setName(""); // NOI18N
        Tbl_op.setRowHeight(20);
        Tbl_op.setSelectionBackground(new java.awt.Color(62, 226, 141));
        Tbl_op.setShowHorizontalLines(false);
        Tbl_op.setShowVerticalLines(false);
        jScrollPane1.setViewportView(Tbl_op);

        jPanel10.add(jScrollPane1);

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 530, 310));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/infosystem/NIELIT-Logo.png"))); // NOI18N
        jPanel12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 90));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("MANAGE COURSES");
        jPanel12.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 440, 40));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to add record?","Add Record",JOptionPane.YES_NO_OPTION);
        if(p==0){
            try{
            String sql="insert into streams"
                    + " (StreamID, StreamType, StreamName,"
                    + " StreamDuration, StreamFees, "
                    + "StrEligibility, Seats) values(?,?,?,?,?,?,?) ";
             pst=conn.prepareStatement(sql);
                pst.setString(1,TF_ID.getText());
                pst.setString(2,TF_Type.getText());
                pst.setString(3,TF_Name.getText());
                pst.setString(4,TF_Duration.getText());
                pst.setString(5,TF_Fees.getText());
                pst.setString(6,TF_Elig.getText());
                pst.setString(7,TF_Seats.getText());
            
             pst.execute();
                JOptionPane.showMessageDialog(null,"Data is saved successfully");

            
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null,e);
            }
            finally {

                try{
                    rs.close();
                    pst.close();

                }  
                
                catch(SQLException e){
                   JOptionPane.showMessageDialog(null,e);
                
            }
        
            }
        }
        Update_table();

    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete?","Delete Record",JOptionPane.YES_NO_OPTION);
        if(p==0){
        
         String sql ="delete from streams where StreamID=? ";
            try{
                pst=conn.prepareStatement(sql);
                pst.setString(1, TF_ID.getText());
                pst.execute();

                JOptionPane.showMessageDialog(null,"Record Deleted");

            }catch(SQLException e){

                JOptionPane.showMessageDialog(null, e);
            }finally {

                try{
                    rs.close();
                    pst.close();

                }
                catch(SQLException e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        Update_table();}
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        TF_Duration.setText("");
        TF_Elig.setText("");
        TF_Fees.setText("");
        TF_ID.setText("");
        TF_Name.setText("");
        TF_Search.setText("");
        TF_Seats.setText("");
        TF_Type.setText("");
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
           int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?","Update Record",JOptionPane.YES_NO_OPTION);
        if(p==0){
              try{

                String value1 = TF_ID.getText();
                String value2 = TF_Name.getText();
                String value3 = TF_Type.getText();
                String value4 = TF_Duration.getText();
                String value5 = TF_Fees.getText();
                String value6 = TF_Elig.getText();
                String value7 = TF_Seats.getText();
                String sql= "update streams"
                        + " set StreamID='"+value1+"',"
                        + " StreamName='"+value2+"',"
                        + "StreamType='"+value3+"'"
                        + ",StreamDuration='"+value4+"'"
                        + ",StreamFees='"+value5+"'"
                        + ",StrEligibility='"+value6+"'"
                        + ",Seats='"+value7+"'"
                        + " where StreamID='"+value1+"' ";

                pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Record Updated");

            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
              finally {

                try{
                    rs.close();
                    pst.close();

                }
                catch(SQLException e){

                }
            }

        }
                Update_table();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        Update_table();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void TF_SearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_SearchKeyPressed
        // TODO add your handling code here:
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        try{
            String sql="select * from streams"
                    + " where StreamID=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, TF_Search.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("StreamName");
                TF_Name.setText(add1);
                String add2=rs.getString("StreamID");
                TF_ID.setText(add2);
                String add3=rs.getString("StreamType");
                TF_Type.setText(add3);
                String add4=rs.getString("StreamDuration");
                TF_Duration.setText(add4);
                String add5=rs.getString("StreamFees");
                TF_Fees.setText(add5);
                String add6=rs.getString("StrEligibility");
                TF_Elig.setText(add6);
                String add7=rs.getString("Seats");
                TF_Seats.setText(add7);
            }
           else if(!TF_Search.equals(rs.next())){
                   JOptionPane.showMessageDialog(null,"No Records Found!","",JOptionPane.ERROR_MESSAGE);
            }
        }
catch(SQLException e){
    JOptionPane.showMessageDialog(null, e);
}}
    }//GEN-LAST:event_TF_SearchKeyPressed
int xx,xy;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
               this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddToCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddToCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddToCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddToCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddToCourses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF_Duration;
    private javax.swing.JTextField TF_Elig;
    private javax.swing.JTextField TF_Fees;
    private javax.swing.JTextField TF_ID;
    private javax.swing.JTextField TF_Name;
    private javax.swing.JTextField TF_Search;
    private javax.swing.JTextField TF_Seats;
    private javax.swing.JTextField TF_Type;
    private javax.swing.JTable Tbl_op;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblSearch;
    private java.util.List<infosystem.Streams> streamsList;
    private javax.persistence.Query streamsQuery;
    // End of variables declaration//GEN-END:variables
}
