/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package infosystem;
import com.sun.glass.events.KeyEvent;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author MayankMS
 */
public class ManageAccnt extends javax.swing.JFrame {
 Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    /**
     * Creates new form ManageAccnt
     */
    public ManageAccnt() {
        initComponents();
        conn=db_conn.java_db();
        Update_table();
    }
  private void Update_table(){
       try{
            String sql="select * from admins";
           pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
       Tbl_op.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(SQLException e){
    JOptionPane.showMessageDialog(null, e);
    }
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_op = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        lbl_add2 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lbl_add1 = new javax.swing.JLabel();
        PW = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        TF_Search = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel13 = new javax.swing.JPanel();
        lbl_add3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lbl_add = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lbl_upd = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lbl_del = new javax.swing.JLabel();
        TF_USER = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        TF_ID = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Training Management System");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(32, 45, 65));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 100, 128));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        Tbl_op.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        Tbl_op.setForeground(new java.awt.Color(51, 51, 51));
        Tbl_op.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        Tbl_op.setEnabled(false);
        Tbl_op.setGridColor(new java.awt.Color(255, 255, 255));
        Tbl_op.setRowHeight(20);
        Tbl_op.setSelectionBackground(new java.awt.Color(62, 226, 141));
        Tbl_op.setShowHorizontalLines(false);
        Tbl_op.setShowVerticalLines(false);
        jScrollPane1.setViewportView(Tbl_op);

        jPanel7.add(jScrollPane1);

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 340, 320));

        jPanel11.setBackground(new java.awt.Color(32, 45, 65));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_add2.setBackground(new java.awt.Color(204, 204, 204));
        lbl_add2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_add2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_add2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_add2.setText("BACK");
        lbl_add2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_add2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_add2MouseClicked(evt);
            }
        });
        jPanel11.add(lbl_add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 20));

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 100, 20));

        jPanel12.setBackground(new java.awt.Color(32, 45, 65));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_add1.setBackground(new java.awt.Color(204, 204, 204));
        lbl_add1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_add1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_add1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_add1.setText("REFRESH");
        lbl_add1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_add1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_add1MouseClicked(evt);
            }
        });
        jPanel12.add(lbl_add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 20));

        jPanel2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 100, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 530));

        PW.setBackground(new java.awt.Color(32, 45, 65));
        PW.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        PW.setForeground(new java.awt.Color(255, 255, 255));
        PW.setBorder(null);
        jPanel1.add(PW, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 190, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PASSWORD");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 140, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 140, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 190, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 190, 10));

        jLabel8.setBackground(new java.awt.Color(32, 45, 65));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SEARCH BY ID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 56, -1, 30));

        TF_Search.setBackground(new java.awt.Color(32, 45, 65));
        TF_Search.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TF_Search.setForeground(new java.awt.Color(255, 255, 255));
        TF_Search.setToolTipText("Press Enter");
        TF_Search.setBorder(null);
        TF_Search.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        TF_Search.setName(""); // NOI18N
        TF_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TF_SearchKeyPressed(evt);
            }
        });
        jPanel1.add(TF_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 190, 20));

        jSeparator4.setBackground(new java.awt.Color(32, 45, 65));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 190, 20));

        jPanel13.setBackground(new java.awt.Color(0, 100, 128));
        jPanel13.setForeground(new java.awt.Color(0, 0, 102));

        lbl_add3.setBackground(new java.awt.Color(204, 204, 204));
        lbl_add3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_add3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_add3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_add3.setText("CLEAR");
        lbl_add3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_add3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_add3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_add3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_add3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 400, 57, -1));

        jPanel10.setBackground(new java.awt.Color(0, 100, 128));
        jPanel10.setForeground(new java.awt.Color(0, 0, 102));

        lbl_add.setBackground(new java.awt.Color(204, 204, 204));
        lbl_add.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_add.setForeground(new java.awt.Color(255, 255, 255));
        lbl_add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_add.setText("ADD");
        lbl_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_add, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_add, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 57, -1));

        jPanel9.setBackground(new java.awt.Color(0, 100, 128));
        jPanel9.setForeground(new java.awt.Color(0, 0, 102));

        lbl_upd.setBackground(new java.awt.Color(29, 40, 46));
        lbl_upd.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_upd.setForeground(new java.awt.Color(255, 255, 255));
        lbl_upd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_upd.setText("UPDATE");
        lbl_upd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_upd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_updMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(lbl_upd, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_upd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 70, -1));

        jPanel8.setBackground(new java.awt.Color(0, 100, 128));
        jPanel8.setForeground(new java.awt.Color(0, 0, 102));

        lbl_del.setBackground(new java.awt.Color(29, 40, 46));
        lbl_del.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_del.setForeground(new java.awt.Color(255, 255, 255));
        lbl_del.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_del.setText("DELETE");
        lbl_del.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_del.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_delMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_del, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_del, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 57, -1));

        TF_USER.setBackground(new java.awt.Color(32, 45, 65));
        TF_USER.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        TF_USER.setForeground(new java.awt.Color(255, 255, 255));
        TF_USER.setBorder(null);
        jPanel1.add(TF_USER, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 190, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("USER NAME");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 140, 20));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 190, 10));

        TF_ID.setBackground(new java.awt.Color(32, 45, 65));
        TF_ID.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        TF_ID.setForeground(new java.awt.Color(255, 255, 255));
        TF_ID.setBorder(null);
        jPanel1.add(TF_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 190, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 920, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/infosystem/NIELIT-Logo.png"))); // NOI18N
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 90));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE ACCOUNTS");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 590, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, -1));

        setBounds(0, 0, 925, 640);
    }// </editor-fold>//GEN-END:initComponents

    private void TF_SearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_SearchKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try{
                String sql="select * from admins where ID=?";
                pst=conn.prepareStatement(sql);
                pst.setString(1, TF_Search.getText());
                rs=pst.executeQuery();
                if(rs.next()){
                    String add1=rs.getString("username");
                    TF_USER.setText(add1);
                    String add2=rs.getString("password");
                   PW.setText(add2);
                    String add3=rs.getString("ID");
                   TF_ID.setText(add3);
                }
               else if(!TF_Search.equals(rs.next())){
                   JOptionPane.showMessageDialog(null,"No Records Found!","",JOptionPane.ERROR_MESSAGE);
                }
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_TF_SearchKeyPressed

    private void lbl_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addMouseClicked
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to add user?","Add Record",JOptionPane.YES_NO_OPTION);
        if(p==0){

            try{
                String sql="insert into admins"
                + " (username,password,ID) values(?,?,?) ";
                pst=conn.prepareStatement(sql);
                pst.setString(1,TF_USER.getText());
                pst.setString(2,PW.getText());
                pst.setString(3,TF_ID.getText());

                pst.execute();
                JOptionPane.showMessageDialog(null,"Data is saved successfully");
            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
            finally {

                try{
                    rs.close();
                    pst.close();

                }

                catch(SQLException e){
                    JOptionPane.showMessageDialog(null,e);

                }

            }

        }
        Update_table();
    }//GEN-LAST:event_lbl_addMouseClicked

    private void lbl_updMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_updMouseClicked
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?","Update Record",JOptionPane.YES_NO_OPTION);
        if(p==0){
            try{

                String value1 = TF_ID.getText();
                String value2 = TF_USER.getText();
                String value3 = PW.getText();
                String sql= "update admins set "
                + " username='"+value2+"',"
                + "password='"+value3+"'"
                + " where ID='"+value1+"' ";

                pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Record Updated");

            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
            finally {

                try{
                    rs.close();
                    pst.close();

                }
                catch(SQLException e){

                }
            }

        }
        Update_table();
    }//GEN-LAST:event_lbl_updMouseClicked

    private void lbl_delMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_delMouseClicked
        // TODO add your handling code here:
        String sql ="delete from admins where ID=? ";
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1, TF_ID.getText());
            pst.execute();

            JOptionPane.showMessageDialog(null,"Record Deleted");

        }catch(SQLException e){

            JOptionPane.showMessageDialog(null, e);
        }finally {

            try{
                rs.close();
                pst.close();

            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        Update_table();
    }//GEN-LAST:event_lbl_delMouseClicked

    private void lbl_add1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_add1MouseClicked
        // TODO add your handling code here:
        Update_table();
    }//GEN-LAST:event_lbl_add1MouseClicked

    private void lbl_add2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_add2MouseClicked
        // TODO add your handling code here:
      this.dispose();
      
    }//GEN-LAST:event_lbl_add2MouseClicked

    private void lbl_add3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_add3MouseClicked
        // TODO add your handling code here:
        TF_USER.setText("");
        PW.setText("");
        TF_ID.setText("");
         TF_Search.setText("");
    }//GEN-LAST:event_lbl_add3MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
               this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageAccnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageAccnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageAccnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageAccnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageAccnt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PW;
    private javax.swing.JTextField TF_ID;
    private javax.swing.JTextField TF_Search;
    private javax.swing.JTextField TF_USER;
    private javax.swing.JTable Tbl_op;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbl_add;
    private javax.swing.JLabel lbl_add1;
    private javax.swing.JLabel lbl_add2;
    private javax.swing.JLabel lbl_add3;
    private javax.swing.JLabel lbl_del;
    private javax.swing.JLabel lbl_upd;
    // End of variables declaration//GEN-END:variables
}
