/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package infosystem;


import javax.swing.JOptionPane;


/**
 *
 * @author MayankMS
 */
public class WelcomeUser extends javax.swing.JFrame {
public static String head;

    /**
     * Creates new form WelcomeUser
     */
    public WelcomeUser() {
        initComponents();
    lblhead.setText(head);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        MNG_CRS = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        S_CRS = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        MNG_ST = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        S_ST = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblhead = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Training Management System");
        setMaximumSize(new java.awt.Dimension(800, 520));
        setMinimumSize(new java.awt.Dimension(800, 520));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(32, 45, 65));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 100, 128));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MANAGE ACCOUNTS");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 100, 128));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LOGOUT");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/infosystem/cogs.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 800, 250));

        jPanel7.setBackground(new java.awt.Color(0, 100, 128));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MNG_CRS.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        MNG_CRS.setForeground(new java.awt.Color(255, 255, 255));
        MNG_CRS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MNG_CRS.setText("MANAGE COURSES");
        MNG_CRS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MNG_CRS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MNG_CRSMouseClicked(evt);
            }
        });
        jPanel7.add(MNG_CRS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));

        jPanel8.setBackground(new java.awt.Color(0, 100, 128));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        S_CRS.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        S_CRS.setForeground(new java.awt.Color(255, 255, 255));
        S_CRS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        S_CRS.setText("SHOW COURSES");
        S_CRS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        S_CRS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S_CRSMouseClicked(evt);
            }
        });
        jPanel8.add(S_CRS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, -1, -1));

        jPanel9.setBackground(new java.awt.Color(0, 100, 128));
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MNG_ST.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        MNG_ST.setForeground(new java.awt.Color(255, 255, 255));
        MNG_ST.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MNG_ST.setText("MANAGE STUDENT");
        MNG_ST.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MNG_ST.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MNG_STMouseClicked(evt);
            }
        });
        jPanel9.add(MNG_ST, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, -1, -1));

        jPanel10.setBackground(new java.awt.Color(0, 100, 128));
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        S_ST.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        S_ST.setForeground(new java.awt.Color(255, 255, 255));
        S_ST.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        S_ST.setText("SHOW STUDENTS");
        S_ST.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        S_ST.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S_STMouseClicked(evt);
            }
        });
        jPanel10.add(S_ST, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/infosystem/NIELIT-Logo.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 100));

        lblhead.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblhead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblhead, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 400, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        ManageAccnt n = new ManageAccnt();
         n.setLocationRelativeTo(null); 
        n.setVisible(true);
      
       
       
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?","Logout",JOptionPane.YES_NO_OPTION);
        if(p==0){
        this.dispose();
        MainWindow m=new MainWindow();
          m.setLocationRelativeTo(null); 
        m.setVisible(true);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void MNG_CRSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MNG_CRSMouseClicked
        // TODO add your handling code here:
        AddToCourses m=new AddToCourses();
          m.setLocationRelativeTo(null); 
        m.setVisible(true);
    }//GEN-LAST:event_MNG_CRSMouseClicked

    private void S_CRSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_CRSMouseClicked
        // TODO add your handling code here:
         ShowCourses m=new ShowCourses();
          m.setLocationRelativeTo(null); 
         m.setVisible(true);
    }//GEN-LAST:event_S_CRSMouseClicked

    private void MNG_STMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MNG_STMouseClicked
        // TODO add your handling code here:
        AddToStudents m=new AddToStudents();
          m.setLocationRelativeTo(null); 
        m.setVisible(true);
    }//GEN-LAST:event_MNG_STMouseClicked
                    

   
    private void S_STMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_STMouseClicked
        // TODO add your handling code here:
      ShowStudents m=new ShowStudents(); 
        m.setLocationRelativeTo(null);   
      m.setVisible(true);
    }//GEN-LAST:event_S_STMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
               this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MNG_CRS;
    private javax.swing.JLabel MNG_ST;
    private javax.swing.JLabel S_CRS;
    private javax.swing.JLabel S_ST;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblhead;
    // End of variables declaration//GEN-END:variables
}
